export type LawDomain = {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  color: string;
  categories: LawCategory[];
};

export type LawCategory = {
  id: string;
  name: string;
  laws: Law[];
};

export type Law = {
  id: string;
  name: string;
  egov_id?: string;
};

export const LAW_DOMAINS: LawDomain[] = [
  {
    id: "public",
    name: "公法",
    nameEn: "Public Law",
    description: "国家と個人の関係を規律する法",
    color: "from-red-900/60 to-red-800/40 border-red-700/50 hover:border-red-500",
    categories: [
      {
        id: "constitutional",
        name: "憲法",
        laws: [
          { id: "kenpo", name: "日本国憲法", egov_id: "321CONSTITUTION" },
          { id: "kenpo-kaisei", name: "憲法改正論・立憲主義" },
          { id: "kokusai-jinken-kouki", name: "国際人権規約（国内適用）" },
        ],
      },
      {
        id: "administrative",
        name: "行政法",
        laws: [
          { id: "gyosei-tetsuzuki", name: "行政手続法", egov_id: "405AC0000000088" },
          { id: "gyosei-fufuku", name: "行政不服申立法", egov_id: "426AC0000000068" },
          { id: "gyosei-jiken", name: "行政事件訴訟法", egov_id: "337AC0000000139" },
          { id: "kokka-baisho", name: "国家賠償法", egov_id: "322AC0000000125" },
          { id: "chiho-jichi", name: "地方自治法", egov_id: "322AC0000000067" },
          { id: "gyosei-daishikko", name: "行政代執行法", egov_id: "323AC0000000043" },
          { id: "joho-kokai", name: "情報公開法", egov_id: "411AC0000000042" },
          { id: "kojin-joho", name: "個人情報保護法", egov_id: "415AC0000000057" },
          { id: "kokka-komuin", name: "国家公務員法", egov_id: "322AC0000000120" },
          { id: "chiho-komuin", name: "地方公務員法", egov_id: "325AC0000000261" },
          { id: "jieitai", name: "自衛隊法", egov_id: "329AC0000000165" },
          { id: "keisatsu", name: "警察法", egov_id: "329AC0000000162" },
          { id: "shobo", name: "消防法", egov_id: "323AC1000000186" },
          { id: "doro-kotsu", name: "道路交通法", egov_id: "335AC0000000105" },
          { id: "koku", name: "航空法", egov_id: "327AC0000000231" },
          { id: "kokuseki", name: "国籍法", egov_id: "325AC0000000147" },
          { id: "nyukan", name: "出入国管理法（入管法）", egov_id: "326CO0000000319" },
          { id: "nanmin-nintei", name: "難民認定法（入管法内）" },
        ],
      },
      {
        id: "election",
        name: "選挙・政治",
        laws: [
          { id: "koushoku-senkyo", name: "公職選挙法", egov_id: "325AC1000000100" },
          { id: "seiji-shikin", name: "政治資金規正法", egov_id: "351AC0000000194" },
          { id: "seitou-joseiho", name: "政党助成法", egov_id: "406AC0000000005" },
          { id: "kokumintohyo", name: "国民投票法", egov_id: "419AC0000000051" },
        ],
      },
      {
        id: "criminal",
        name: "刑法",
        laws: [
          { id: "keiho-soron", name: "刑法総論", egov_id: "140AC0000000045" },
          { id: "keiho-kakuron", name: "刑法各論", egov_id: "140AC0000000045" },
          { id: "sosoki", name: "組織的犯罪処罰法", egov_id: "411AC0000000136" },
          { id: "yakubutsu", name: "覚醒剤取締法", egov_id: "326AC0100000252" },
          { id: "dv-bo", name: "DV防止法", egov_id: "413AC0100000031" },
          { id: "strker-kisei", name: "ストーカー規制法", egov_id: "412AC0100000081" },
          { id: "saiban-in", name: "裁判員法", egov_id: "416AC0000000063" },
          { id: "boryokudan", name: "暴力団対策法", egov_id: "403AC0000000077" },
          { id: "kokkyo-hanzai", name: "国境を越える犯罪（条約犯罪）" },
          { id: "cyber-crime", name: "サイバー犯罪条約・不正アクセス禁止法", egov_id: "411AC0000000128" },
        ],
      },
      {
        id: "juvenile",
        name: "少年法",
        laws: [
          { id: "shonen-ho", name: "少年法", egov_id: "323AC0000000168" },
          { id: "jido-fukushi", name: "児童福祉法", egov_id: "322AC0000000164" },
          { id: "jido-gyakutai", name: "児童虐待防止法", egov_id: "412AC1000000082" },
          { id: "kodomo-kihon", name: "こども基本法", egov_id: "504AC1000000077" },
          { id: "ijime-boshi", name: "いじめ防止対策推進法", egov_id: "425AC1000000071" },
          { id: "wakamono-shien", name: "子ども・若者育成支援推進法", egov_id: "421AC0000000071" },
          { id: "kodomo-hinkon", name: "子どもの貧困対策法", egov_id: "425AC0000000064" },
        ],
      },
      {
        id: "tax",
        name: "税法",
        laws: [
          { id: "shotoku-zei", name: "所得税法", egov_id: "340AC0000000033" },
          { id: "hojin-zei", name: "法人税法", egov_id: "340AC0000000034" },
          { id: "shohizei", name: "消費税法", egov_id: "363AC0000000108" },
          { id: "sozoku-zei", name: "相続税法", egov_id: "325AC0000000073" },
          { id: "kokuzei-tsusoku", name: "国税通則法", egov_id: "337AC0000000066" },
          { id: "kokuzei-choshu", name: "国税徴収法", egov_id: "334AC0000000147" },
          { id: "chiho-zei", name: "地方税法", egov_id: "325AC0000000226" },
          { id: "sozei-tokubetsu", name: "租税特別措置法", egov_id: "332AC0000000026" },
          { id: "zeimu-dairi", name: "税理士法", egov_id: "326AC1000000237" },
        ],
      },
      {
        id: "transport",
        name: "交通・運輸法",
        laws: [
          { id: "doro-unso", name: "道路運送法", egov_id: "326AC0000000183" },
          { id: "tetsudo-jigyo", name: "鉄道事業法", egov_id: "361AC0000000092" },
          { id: "kaijo-unso", name: "海上運送法", egov_id: "324AC0000000187" },
          { id: "koku-ho", name: "航空法", egov_id: "327AC0000000231" },
          { id: "jibaiseki", name: "自動車損害賠償保障法（自賠責）", egov_id: "330AC0000000097" },
          { id: "doro-ho", name: "道路法", egov_id: "327AC1000000180" },
          { id: "kotsujiko-taisaku", name: "交通事故処理特例法" },
          { id: "funsen", name: "船舶法・船員法" },
        ],
      },
      {
        id: "energy",
        name: "エネルギー法",
        laws: [
          { id: "denki-jigyo", name: "電気事業法", egov_id: "339AC0000000170" },
          { id: "gas-jigyo", name: "ガス事業法", egov_id: "329AC0000000051" },
          { id: "genshiryoku-kihon", name: "原子力基本法", egov_id: "330AC1000000186" },
          { id: "genshiryoku-kisei", name: "原子炉等規制法", egov_id: "332AC0000000166" },
          { id: "fit-ho", name: "再生可能エネルギー促進法（FIT法）", egov_id: "423AC0000000108" },
          { id: "shoene-ho", name: "省エネ法（エネルギーの使用の合理化法）" },
          { id: "sekiyu-ho", name: "石油備蓄法・石油業法" },
        ],
      },
      {
        id: "foreign-trade",
        name: "外事・安全保障輸出管理",
        laws: [
          { id: "gaito-ho", name: "外国為替及び外国貿易法（外為法）", egov_id: "324AC0000000228" },
          { id: "yushutsu-kanri", name: "輸出貿易管理令・外国為替令" },
          { id: "keizai-anpo-ho", name: "経済安全保障推進法", egov_id: "504AC0000000043" },
          { id: "toshi-kisei", name: "対内直接投資規制（外為法52条以下）" },
          { id: "seigen-measures", name: "経済制裁・資産凍結措置" },
        ],
      },
    ],
  },
  {
    id: "private",
    name: "私法",
    nameEn: "Private Law",
    description: "私人間の権利・義務関係を規律する法",
    color: "from-blue-900/60 to-blue-800/40 border-blue-700/50 hover:border-blue-500",
    categories: [
      {
        id: "civil",
        name: "民法",
        laws: [
          { id: "minpo-soron", name: "民法総則", egov_id: "129AC0000000089" },
          { id: "minpo-bukken", name: "民法（物権）", egov_id: "129AC0000000089" },
          { id: "minpo-tanpo", name: "民法（担保物権）", egov_id: "129AC0000000089" },
          { id: "minpo-saiken", name: "民法（債権総論）", egov_id: "129AC0000000089" },
          { id: "minpo-kakushu", name: "民法（各種契約）", egov_id: "129AC0000000089" },
          { id: "minpo-jiko", name: "民法（不法行為・不当利得）", egov_id: "129AC0000000089" },
          { id: "minpo-kazoku", name: "民法（親族・相続）", egov_id: "129AC0000000089" },
          { id: "fudosan-toroki", name: "不動産登記法", egov_id: "416AC0000000123" },
          { id: "shakuchi-shakka", name: "借地借家法", egov_id: "403AC0000000090" },
          { id: "kokkyo-tatemono", name: "区分所有法", egov_id: "337AC0000000069" },
          { id: "shintaku", name: "信託法", egov_id: "418AC0000000108" },
          { id: "hasan", name: "破産法", egov_id: "416AC0000000075" },
          { id: "minzi-saisei", name: "民事再生法", egov_id: "411AC0000000225" },
          { id: "kaisha-kosei", name: "会社更生法", egov_id: "414AC0000000154" },
          { id: "doshi-saiken", name: "動産・債権譲渡特例法", egov_id: "410AC0000000104" },
          { id: "denshi-kiroku-saiken", name: "電子記録債権法", egov_id: "419AC0000000102" },
          { id: "seineikouken", name: "成年後見制度（民法・関連法）" },
        ],
      },
      {
        id: "commercial",
        name: "商法・会社法",
        laws: [
          { id: "shoho-soron", name: "商法総則・商行為", egov_id: "132AC0000000048" },
          { id: "kaisha-soron", name: "会社法（総則・設立）", egov_id: "417AC0000000086" },
          { id: "kaisha-kabushiki", name: "会社法（株式・新株予約権）", egov_id: "417AC0000000086" },
          { id: "kaisha-kikan", name: "会社法（機関）", egov_id: "417AC0000000086" },
          { id: "kaisha-kaikei", name: "会社法（計算・解散）", egov_id: "417AC0000000086" },
          { id: "kaisha-henshin", name: "会社法（組織再編）", egov_id: "417AC0000000086" },
          { id: "tegata", name: "手形法", egov_id: "307AC0000000020" },
          { id: "kogitte", name: "小切手法", egov_id: "308AC0000000057" },
          { id: "hoken", name: "保険法", egov_id: "420AC0000000056" },
          { id: "kaijo", name: "商法（海商）", egov_id: "132AC0000000048" },
          { id: "kingyu-shohin", name: "金融商品取引法", egov_id: "323AC0000000025" },
          { id: "dokusen-kinshi", name: "独占禁止法", egov_id: "322AC0000000054" },
          { id: "fusei-kyoso", name: "不正競争防止法", egov_id: "405AC0000000047" },
          { id: "shohi-keiyaku", name: "消費者契約法", egov_id: "412AC0000000061" },
          { id: "halloppa", name: "割賦販売法", egov_id: "336AC0000000159" },
          { id: "tokutei-shoho", name: "特定商取引法", egov_id: "351AC0000000057" },
          { id: "kashikin", name: "貸金業法", egov_id: "358AC1000000032" },
          { id: "servicer", name: "サービサー法", egov_id: "410AC1000000126" },
          { id: "fintec", name: "銀行法・資金移動業" },
        ],
      },
      {
        id: "intellectual",
        name: "知的財産法",
        laws: [
          { id: "tokkyo", name: "特許法", egov_id: "334AC0000000121" },
          { id: "jitsuyoann", name: "実用新案法", egov_id: "334AC0000000123" },
          { id: "isho", name: "意匠法", egov_id: "334AC0000000125" },
          { id: "shouhyo", name: "商標法", egov_id: "334AC0000000127" },
          { id: "chosakuken", name: "著作権法", egov_id: "345AC0000000048" },
          { id: "shubyo", name: "種苗法", egov_id: "416AC0000000083" },
          { id: "half-conductor", name: "半導体集積回路法" },
          { id: "chizai-kozan", name: "鉱業法（先願主義・知財との関連）" },
        ],
      },
      {
        id: "corporate-accounting",
        name: "企業会計法",
        laws: [
          { id: "kigyokaikei-kijun", name: "企業会計原則・会計基準（GAAP）" },
          { id: "ifrs", name: "国際財務報告基準（IFRS）" },
          { id: "kaisha-keisankiroku", name: "会社計算規則" },
          { id: "kinyu-shohin-kaikei", name: "金融商品に係る会計基準" },
          { id: "j-sox", name: "内部統制報告制度（J-SOX）" },
          { id: "kansa-kijun", name: "監査基準・公認会計士法", egov_id: "323AC0000000103" },
          { id: "zeimu-kaikei", name: "税務会計（法人税法との関係）" },
          { id: "disclosure-kisei", name: "有価証券報告書・開示規制" },
        ],
      },
      {
        id: "insolvency",
        name: "倒産処理法",
        laws: [
          { id: "hasan2", name: "破産法（個人・法人破産）", egov_id: "416AC0000000075" },
          { id: "minzi-saisei2", name: "民事再生法（事業再生・個人再生）", egov_id: "411AC0000000225" },
          { id: "kaisha-kosei2", name: "会社更生法", egov_id: "414AC0000000154" },
          { id: "tokubetsu-seisan", name: "特別清算（会社法）" },
          { id: "shiteki-seiri", name: "私的整理ガイドライン・ADR手続" },
          { id: "kinyu-kikan-hatan", name: "預金保険法・金融機関の破綻処理", egov_id: "346AC0000000034" },
          { id: "saiken-kanri", name: "債権管理・担保権実行と倒産手続" },
        ],
      },
      {
        id: "financial-law",
        name: "金融法",
        laws: [
          { id: "ginko-ho", name: "銀行法", egov_id: "356AC0000000059" },
          { id: "kinyu-shohin-ho", name: "金融商品取引法（総合）", egov_id: "323AC0000000025" },
          { id: "hoken-gyoho", name: "保険業法", egov_id: "407AC0000000105" },
          { id: "shintaku-gyoho", name: "信託業法", egov_id: "416AC0000000154" },
          { id: "kashikin-gyoho", name: "貸金業法", egov_id: "358AC1000000032" },
          { id: "shikin-kessai-ho", name: "資金決済法（送金・前払・暗号資産）", egov_id: "421AC0000000059" },
          { id: "kinyu-saisei-ho", name: "金融機能の再生のための緊急措置法" },
          { id: "kinyu-kisei", name: "金融規制・バーゼル規制（国際基準）" },
        ],
      },
      {
        id: "construction-realestate",
        name: "建設・不動産業法",
        laws: [
          { id: "takken-gyoho", name: "宅地建物取引業法（宅建業法）" },
          { id: "kensetsu-gyoho", name: "建設業法", egov_id: "324AC0000000100" },
          { id: "kenchikushi-ho", name: "建築士法", egov_id: "325AC1000000202" },
          { id: "tochi-tatemono-torihiki", name: "土地・建物の売買契約実務" },
          { id: "tochi-shuyou", name: "土地収用法", egov_id: "326AC0100000219" },
          { id: "manshon-kanri", name: "マンション管理適正化法" },
          { id: "kodan-jutaku", name: "住宅品質確保法・瑕疵担保履行法" },
        ],
      },
      {
        id: "everyday",
        name: "生活の法律",
        laws: [
          { id: "chintai-trouble", name: "賃貸・住宅トラブル（敷金・退去・修繕）" },
          { id: "baito-trouble", name: "バイト・労働トラブル（未払い・不当解雇）" },
          { id: "shohi-higai", name: "消費者被害・詐欺・悪徳商法" },
          { id: "net-meiyokison", name: "ネット誹謗中傷・プライバシー侵害" },
          { id: "kotsu-jiko", name: "交通事故・損害賠償" },
          { id: "shakkin-hasan", name: "借金・過払い金・自己破産" },
          { id: "rikon-seikatsu", name: "離婚・財産分与・親権" },
          { id: "souzoku-nichijo", name: "相続・遺言・遺産分割" },
          { id: "iv-trouble", name: "DV・ハラスメント被害と法的手段" },
          { id: "sns-chosakuken", name: "SNS・著作権・肖像権の日常問題" },
        ],
      },
    ],
  },
  {
    id: "procedural",
    name: "訴訟法",
    nameEn: "Procedural Law",
    description: "権利実現のための手続を定める法",
    color: "from-purple-900/60 to-purple-800/40 border-purple-700/50 hover:border-purple-500",
    categories: [
      {
        id: "civil-procedure",
        name: "民事訴訟・執行・保全",
        laws: [
          { id: "minsosho", name: "民事訴訟法", egov_id: "408AC0000000109" },
          { id: "minsikko", name: "民事執行法", egov_id: "354AC0000000004" },
          { id: "minhozen", name: "民事保全法", egov_id: "401AC0000000091" },
          { id: "minji-chosei", name: "民事調停法", egov_id: "326AC1000000222" },
          { id: "kazoku-jiken", name: "家事事件手続法", egov_id: "423AC0000000052" },
          { id: "chusai", name: "仲裁法", egov_id: "415AC0000000138" },
          { id: "adr", name: "ADR促進法", egov_id: "416AC0000000151" },
          { id: "kokusai-minsosho-tetsuzuki", name: "国際民事訴訟手続" },
        ],
      },
      {
        id: "criminal-procedure",
        name: "刑事訴訟法",
        laws: [
          { id: "keisosho", name: "刑事訴訟法", egov_id: "323AC0000000131" },
          { id: "keiji-shikko", name: "刑事収容施設法", egov_id: "417AC0000000050" },
          { id: "higaisha-hogo", name: "犯罪被害者等保護法", egov_id: "411AC0000000075" },
          { id: "higaisha-kyufu", name: "犯罪被害者給付金支給法", egov_id: "355AC0000000036" },
        ],
      },
      {
        id: "court",
        name: "裁判所・法曹",
        laws: [
          { id: "saibansho", name: "裁判所法", egov_id: "322AC0000000059" },
          { id: "bengoshi", name: "弁護士法", egov_id: "324AC1000000205" },
          { id: "shiho-shoshi", name: "司法書士法", egov_id: "325AC1000000197" },
          { id: "gyosei-shoshi-ho", name: "行政書士法", egov_id: "326AC1000000004" },
          { id: "benrishi", name: "弁理士法", egov_id: "412AC0000000049" },
          { id: "zeirishi", name: "税理士法", egov_id: "326AC1000000237" },
          { id: "cpa", name: "公認会計士法", egov_id: "323AC0000000103" },
        ],
      },
    ],
  },
  {
    id: "social",
    name: "社会法",
    nameEn: "Social Law",
    description: "社会的弱者保護・公正な社会を実現する法",
    color: "from-green-900/60 to-green-800/40 border-green-700/50 hover:border-green-500",
    categories: [
      {
        id: "labor",
        name: "労働法",
        laws: [
          { id: "rodo-kijun", name: "労働基準法", egov_id: "322AC0000000049" },
          { id: "rodo-keiyaku", name: "労働契約法", egov_id: "419AC0000000128" },
          { id: "rodo-kumiai", name: "労働組合法", egov_id: "324AC0000000174" },
          { id: "rodo-kankei-chosei", name: "労働関係調整法", egov_id: "321AC0000000025" },
          { id: "koyo-kinto", name: "男女雇用機会均等法", egov_id: "347AC0000000113" },
          { id: "ikuji-kaigo", name: "育児・介護休業法", egov_id: "403AC0000000076" },
          { id: "rodo-anzen", name: "労働安全衛生法", egov_id: "347AC0000000057" },
          { id: "haken-rodo", name: "労働者派遣法", egov_id: "360AC0000000088" },
          { id: "saiyo-antei", name: "職業安定法", egov_id: "322AC0000000141" },
          { id: "saichin", name: "最低賃金法", egov_id: "334AC0000000137" },
          { id: "pato-rodo", name: "パートタイム・有期雇用労働法", egov_id: "405AC0000000076" },
          { id: "rodo-shinpan", name: "労働審判法", egov_id: "416AC0000000045" },
          { id: "kogaisha-hogo", name: "公益通報者保護法", egov_id: "416AC0000000122" },
          { id: "gender-pay", name: "同一労働同一賃金（女性活躍推進法）" },
        ],
      },
      {
        id: "gender",
        name: "ジェンダー法",
        laws: [
          { id: "danjo-sankaku", name: "男女共同参画社会基本法", egov_id: "411AC0000000078" },
          { id: "josei-katsuyaku", name: "女性活躍推進法", egov_id: "427AC0000000064" },
          { id: "dv-shakai", name: "DV防止法（社会法的観点）", egov_id: "413AC0100000031" },
          { id: "gender-identity", name: "性同一性障害者特例法", egov_id: "416AC0000000111" },
          { id: "lgbt-rikai", name: "LGBT理解増進法", egov_id: "505AC1000000068" },
          { id: "sekuhara", name: "セクハラ・マタハラ防止（均等法）" },
          { id: "marriage-equality", name: "婚姻の平等（議論・判例）" },
          { id: "fufu-betsusei", name: "選択的夫婦別姓（議論・判例）" },
          { id: "gender-pay-gap", name: "ジェンダー賃金格差と法的是正" },
          { id: "seitekishoko-ho", name: "性的指向・性自認に関する法的保護" },
          { id: "sekusyuaru-consent", name: "性的同意と刑法改正（2023年）" },
          { id: "gender-kokusai", name: "国際的なジェンダー平等規範（CEDAW等）" },
          { id: "seisansei-ho", name: "生殖補助医療・人工授精と法" },
          { id: "gender-sport", name: "スポーツにおけるジェンダー平等" },
        ],
      },
      {
        id: "disability-elderly",
        name: "障害者・高齢者法",
        laws: [
          { id: "shougaisha-sabetsu", name: "障害者差別解消法", egov_id: "425AC0000000065" },
          { id: "shougaisha-shien", name: "障害者総合支援法", egov_id: "417AC0000000123" },
          { id: "shougaisha-koyo", name: "障害者雇用促進法", egov_id: "335AC0000000123" },
          { id: "koreisha-fukushi", name: "老人福祉法", egov_id: "338AC0000000133" },
          { id: "kaigo-hoken", name: "介護保険法", egov_id: "409AC0000000123" },
          { id: "koreisha-gyakutai", name: "高齢者虐待防止法", egov_id: "417AC0000000124" },
          { id: "seineikouken2", name: "成年後見制度の利用促進法", egov_id: "428AC0000000029" },
        ],
      },
      {
        id: "social-security",
        name: "社会保障法",
        laws: [
          { id: "kenko-hoken", name: "健康保険法", egov_id: "211AC0000000070" },
          { id: "kosei-nenkin", name: "厚生年金保険法", egov_id: "329AC0000000115" },
          { id: "kokumin-nenkin", name: "国民年金法", egov_id: "334AC0000000141" },
          { id: "koyo-hoken", name: "雇用保険法", egov_id: "349AC0000000116" },
          { id: "rodo-sha-saigai", name: "労災保険法", egov_id: "322AC0000000050" },
          { id: "seikatsuhogo", name: "生活保護法", egov_id: "325AC0000000144" },
          { id: "jidou-teate", name: "児童手当法", egov_id: "346AC0000000073" },
          { id: "boshi-katei", name: "母子及び父子並びに寡婦福祉法", egov_id: "339AC0000000129" },
        ],
      },
      {
        id: "environmental",
        name: "環境法（国内）",
        laws: [
          { id: "kankyo-kihon", name: "環境基本法", egov_id: "405AC0000000091" },
          { id: "taiki-osen", name: "大気汚染防止法", egov_id: "343AC0000000097" },
          { id: "suishitsu-odaku", name: "水質汚濁防止法", egov_id: "345AC0000000138" },
          { id: "junkan-shakai", name: "循環型社会形成推進基本法", egov_id: "412AC0000000110" },
          { id: "haikibutsu", name: "廃棄物処理法", egov_id: "345AC0000000137" },
          { id: "dojo-osen", name: "土壌汚染対策法", egov_id: "414AC0000000053" },
          { id: "ondanka-taisaku", name: "地球温暖化対策推進法", egov_id: "410AC0000000117" },
          { id: "shizen-hogo", name: "自然環境保全法", egov_id: "347AC0000000085" },
          { id: "tori-choju", name: "鳥獣保護管理法", egov_id: "414AC0000000088" },
          { id: "toshi-keikaku", name: "都市計画法", egov_id: "343AC0000000100" },
          { id: "kenchiku-kijun", name: "建築基準法", egov_id: "325AC0000000201" },
          { id: "nochi", name: "農地法", egov_id: "327AC0000000229" },
        ],
      },
      {
        id: "medical",
        name: "医事法・保健法",
        laws: [
          { id: "ishi-ho", name: "医師法", egov_id: "323AC0000000201" },
          { id: "iryo-ho", name: "医療法", egov_id: "323AC0000000205" },
          { id: "yakki-ho", name: "薬機法（医薬品医療機器等法）", egov_id: "335AC0000000145" },
          { id: "seishin-hoken", name: "精神保健福祉法", egov_id: "325AC0100000123" },
          { id: "zoki-ishoku", name: "臓器移植法", egov_id: "409AC1000000104" },
          { id: "kansen-sho-ho", name: "感染症法（感染症予防法）", egov_id: "410AC0000000114" },
          { id: "iryo-ayamachi", name: "医療過誤・医療訴訟" },
          { id: "kango-ho", name: "保健師助産師看護師法", egov_id: "323AC0000000203" },
          { id: "shakai-hoken-iryou", name: "健康保険・医療保険制度" },
          { id: "kinen-ho", name: "健康増進法（受動喫煙規制）", egov_id: "414AC0000000103" },
        ],
      },
      {
        id: "education",
        name: "教育法",
        laws: [
          { id: "kyoiku-kihon", name: "教育基本法", egov_id: "418AC0000000120" },
          { id: "gakko-kyoiku", name: "学校教育法", egov_id: "322AC0000000026" },
          { id: "shiritsu-gakko", name: "私立学校法", egov_id: "324AC0000000270" },
          { id: "daigaku-ho", name: "大学設置基準・学校法人法" },
          { id: "kyoshoku", name: "教育職員免許法・教師の法的地位" },
          { id: "gakusei-seikatsu", name: "学生の権利・退学・懲戒処分" },
          { id: "bunkyo-sisaku", name: "文部科学省の教育行政・文化政策" },
        ],
      },
      {
        id: "food-agriculture",
        name: "食品・農林水産法",
        laws: [
          { id: "shokuhin-eisei", name: "食品衛生法", egov_id: "322AC0000000233" },
          { id: "shokuhin-anzen", name: "食品安全基本法", egov_id: "415AC0000000048" },
          { id: "jas-ho", name: "JAS法（農林物資の規格化）", egov_id: "325AC0000000175" },
          { id: "keihyo-ho", name: "景品表示法（食品表示偽装）", egov_id: "337AC0000000134" },
          { id: "gyogyo-ho", name: "漁業法", egov_id: "324AC0000000267" },
          { id: "ringyo-kihon", name: "森林法・林業基本法" },
          { id: "nogyo-keiei", name: "農業経営基盤強化促進法" },
          { id: "shokuhin-label", name: "食品表示法", egov_id: "425AC0000000070" },
        ],
      },
      {
        id: "npo-nonprofit",
        name: "NPO・公益法人法",
        laws: [
          { id: "npo-ho", name: "特定非営利活動促進法（NPO法）", egov_id: "410AC1000000007" },
          { id: "koeki-hojin", name: "公益社団法人及び公益財団法人認定法", egov_id: "418AC0000000049" },
          { id: "shakai-fukushi-hojin", name: "社会福祉法・社会福祉法人", egov_id: "326AC0000000045" },
          { id: "kyodo-kumiai", name: "協同組合法（農協・生協・信用組合）" },
          { id: "zaidan-hojin", name: "一般社団法人・財団法人法", egov_id: "418AC0000000048" },
          { id: "kifu-kisei", name: "寄付金・クラウドファンディングの規制" },
        ],
      },
    ],
  },
  {
    id: "international",
    name: "国際法",
    nameEn: "International Law",
    description: "国家間・国際社会を規律する法",
    color: "from-cyan-900/60 to-cyan-800/40 border-cyan-700/50 hover:border-cyan-500",
    categories: [
      {
        id: "public-international",
        name: "国際公法",
        laws: [
          { id: "kokusai-joyaku", name: "条約法に関するウィーン条約" },
          { id: "kokuren-kensho", name: "国際連合憲章" },
          { id: "kokusai-siko", name: "国家責任条文（ILC草案）" },
          { id: "gaiko-tokken", name: "外交関係に関するウィーン条約" },
          { id: "ryoji-tokken", name: "領事関係に関するウィーン条約" },
          { id: "kaiyoho", name: "海洋法条約（UNCLOS）" },
          { id: "kouku-joyaku", name: "国際民間航空条約（シカゴ条約）" },
          { id: "uchu-joyaku", name: "宇宙条約" },
        ],
      },
      {
        id: "human-rights-international",
        name: "国際人権法",
        laws: [
          { id: "jiyuken-kitei", name: "自由権規約（ICCPR）" },
          { id: "shakaikenk-itei", name: "社会権規約（ICESCR）" },
          { id: "joshi-sabetsu", name: "女性差別撤廃条約（CEDAW）" },
          { id: "jinshu-sabetsu", name: "人種差別撤廃条約（ICERD）" },
          { id: "kodomo-kenri", name: "子どもの権利条約（CRC）" },
          { id: "shogaisha-kenri", name: "障害者権利条約（CRPD）" },
          { id: "gomon-kinshi", name: "拷問等禁止条約（CAT）" },
          { id: "nanmin-joyaku2", name: "難民条約・議定書" },
          { id: "ianfu-mondai", name: "慰安婦問題と国際人権法" },
        ],
      },
      {
        id: "humanitarian",
        name: "国際人道法",
        laws: [
          { id: "geneva", name: "ジュネーブ諸条約（4条約＋議定書）" },
          { id: "hague-bunka", name: "ハーグ条約（文化財保護）" },
          { id: "jirai-kinshi", name: "対人地雷全面禁止条約（オタワ条約）" },
          { id: "cluster-dan", name: "クラスター弾に関する条約" },
          { id: "kakuheiki", name: "核兵器禁止条約（TPNW）" },
          { id: "kagaku-heiki", name: "化学兵器禁止条約（CWC）" },
        ],
      },
      {
        id: "international-criminal",
        name: "国際刑事法",
        laws: [
          { id: "rome-kitei", name: "ローマ規程（ICC）" },
          { id: "hikiawase-joyaku", name: "犯罪人引渡し条約" },
          { id: "kokusai-keiji-kyoryoku", name: "国際刑事共助法", egov_id: "355AC0000000069" },
          { id: "palermo-joyaku", name: "国際組織犯罪防止条約（パレルモ条約）" },
          { id: "tero-shikin", name: "テロ資金供与防止条約" },
        ],
      },
      {
        id: "international-environmental",
        name: "国際環境法",
        laws: [
          { id: "paris-kyotei", name: "パリ協定（気候変動）" },
          { id: "unfccc", name: "国連気候変動枠組条約（UNFCCC）" },
          { id: "kyoto-giteisho", name: "京都議定書" },
          { id: "seidai-tayosei", name: "生物多様性条約（CBD）" },
          { id: "nagoya-giteisho", name: "名古屋議定書（遺伝資源）" },
          { id: "basel-joyaku", name: "バーゼル条約（有害廃棄物）" },
          { id: "stockholm-joyaku", name: "ストックホルム条約（POPs）" },
          { id: "minamata-joyaku", name: "水俣条約（水銀）" },
          { id: "ramsar-joyaku", name: "ラムサール条約（湿地）" },
          { id: "washington-joyaku", name: "ワシントン条約（CITES・野生生物）" },
          { id: "ozone-layer", name: "ウィーン条約・モントリオール議定書（オゾン）" },
          { id: "unccd", name: "砂漠化対処条約（UNCCD）" },
          { id: "kunming-montreal", name: "昆明・モントリオール生物多様性枠組" },
          { id: "loss-damage", name: "損失と損害（Loss and Damage）基金" },
          { id: "environment-jus-cogens", name: "環境権の国際法的位置づけ" },
          { id: "ecocide", name: "エコサイド（生態系破壊）の国際刑事責任" },
          { id: "climate-sosho-intl", name: "気候変動訴訟の国際動向" },
        ],
      },
      {
        id: "private-international",
        name: "国際私法",
        laws: [
          { id: "horei", name: "法の適用に関する通則法", egov_id: "418AC0000000078" },
          { id: "kokusai-minsosho", name: "国際民事訴訟法" },
          { id: "cisg", name: "CISG（国際物品売買条約）" },
          { id: "new-york-joyaku", name: "ニューヨーク条約（外国仲裁判断承認）" },
          { id: "hague-kankatsu", name: "ハーグ条約（国際裁判管轄）" },
          { id: "hague-kodomo", name: "ハーグ条約（国際的な子の奪取）" },
        ],
      },
      {
        id: "trade-international",
        name: "国際経済法",
        laws: [
          { id: "wto", name: "WTO協定・GATT" },
          { id: "gats", name: "サービス貿易協定（GATS）" },
          { id: "fta-epa", name: "FTA・EPA（日米・日EU・RCEP等）" },
          { id: "isds", name: "投資協定・ISDS条項" },
          { id: "kokusai-tokkyo", name: "PCT（特許協力条約）" },
          { id: "trips", name: "TRIPS協定（知財）" },
          { id: "icts", name: "ITA協定（情報技術協定）" },
        ],
      },
      {
        id: "foreign-law",
        name: "外国の法律",
        laws: [
          { id: "us-law", name: "アメリカ法（憲法・判例法主義・契約法）" },
          { id: "eu-law", name: "EU法（欧州人権条約・GDPR・競争法）" },
          { id: "uk-law", name: "イギリス法（コモンロー・衡平法）" },
          { id: "german-law", name: "ドイツ法（民法典・連邦憲法裁判所）" },
          { id: "french-law", name: "フランス法（ナポレオン民法典・行政法）" },
          { id: "china-law", name: "中国法（民法典・刑法・国家安全法）" },
          { id: "korea-law", name: "韓国法（民法・憲法・労働法）" },
          { id: "islamic-law", name: "イスラム法（シャリーア）" },
          { id: "un-law", name: "国連・国際機関の法規範・決議" },
        ],
      },
    ],
  },
  {
    id: "digital",
    name: "デジタル法",
    nameEn: "Digital Law",
    description: "IT・AI・データなど新技術分野の法規制",
    color: "from-amber-900/60 to-amber-800/40 border-amber-700/50 hover:border-amber-500",
    categories: [
      {
        id: "digital-general",
        name: "情報・通信法",
        laws: [
          { id: "fusei-access", name: "不正アクセス禁止法", egov_id: "411AC0000000128" },
          { id: "denshi-shomu", name: "電子署名法", egov_id: "412AC0000000102" },
          { id: "it-kihon", name: "デジタル社会形成基本法", egov_id: "503AC0000000035" },
          { id: "kojin-joho-digital", name: "個人情報保護法（デジタル）", egov_id: "415AC0000000057" },
          { id: "provider-sekinin", name: "プロバイダ責任制限法", egov_id: "413AC0000000137" },
          { id: "denki-tsushin", name: "電気通信事業法", egov_id: "359AC0000000086" },
          { id: "hoso-ho", name: "放送法", egov_id: "325AC0000000132" },
          { id: "sns-kisei", name: "SNS・プラットフォーム規制（最新動向）" },
        ],
      },
      {
        id: "fintech",
        name: "フィンテック・金融デジタル",
        laws: [
          { id: "crypto-asset", name: "資金決済法（暗号資産）", egov_id: "421AC0000000059" },
          { id: "denshi-money", name: "電子マネー・前払式支払手段" },
          { id: "stablecoin", name: "ステーブルコイン規制（資金決済法改正）" },
          { id: "nft-kisoku", name: "NFT・デジタル資産の法的性質" },
        ],
      },
      {
        id: "ai-data",
        name: "AI・データ法",
        laws: [
          { id: "ai-kisoku", name: "AI関連法規・ガイドライン（最新動向）" },
          { id: "data-riyou", name: "データ利活用法（産業競争力強化法等）" },
          { id: "algorithmic-accountability", name: "アルゴリズム規制・説明責任" },
          { id: "eu-ai-act", name: "EU AI Act（域外適用）" },
          { id: "drone-kisoku", name: "航空法（ドローン規制）", egov_id: "327AC0000000231" },
          { id: "jidounten", name: "自動運転関連法規" },
        ],
      },
      {
        id: "space-law",
        name: "宇宙法・先端科学法",
        laws: [
          { id: "uchu-kihon", name: "宇宙基本法", egov_id: "420AC0000000043" },
          { id: "uchu-katsudo", name: "宇宙活動法（人工衛星等打上法）", egov_id: "428AC0000000076" },
          { id: "eisei-remote", name: "衛星リモートセンシング記録法", egov_id: "428AC0000000077" },
          { id: "uchu-joyaku2", name: "宇宙条約・月協定（国際宇宙法）" },
          { id: "nano-bio-ho", name: "ナノテク・バイオ・ゲノム規制" },
          { id: "quantum-ho", name: "量子技術・量子コンピュータ規制動向" },
        ],
      },
      {
        id: "media-law",
        name: "メディア・放送法",
        laws: [
          { id: "hoso-ho2", name: "放送法", egov_id: "325AC0000000132" },
          { id: "denpa-ho", name: "電波法", egov_id: "325AC0000000131" },
          { id: "nhk-ho", name: "NHK・公共放送の法的地位" },
          { id: "press-jiyuu", name: "報道の自由・記者クラブ問題" },
          { id: "kokoku-kisei", name: "広告規制・景品表示法" },
          { id: "sns-platform-kisei", name: "SNSプラットフォーム規制の最新動向" },
        ],
      },
    ],
  },
  {
    id: "human-rights",
    name: "人権法",
    nameEn: "Human Rights Law",
    description: "基本的人権・差別禁止・救済を定める法",
    color: "from-rose-900/60 to-rose-800/40 border-rose-700/50 hover:border-rose-500",
    categories: [
      {
        id: "discrimination",
        name: "差別禁止法",
        laws: [
          { id: "hate-speech", name: "ヘイトスピーチ解消法", egov_id: "428AC0100000068" },
          { id: "buraku-sabetsu", name: "部落差別解消推進法", egov_id: "428AC1000000109" },
          { id: "jinshu-sabetsu-kokurai", name: "人種差別撤廃条約（国内実施）" },
          { id: "shogaisha-sabetsu2", name: "障害者差別解消法", egov_id: "425AC0000000065" },
          { id: "koyo-kinto2", name: "雇用機会均等法（差別禁止）", egov_id: "347AC0000000113" },
        ],
      },
      {
        id: "relief",
        name: "権利救済・被害者支援",
        laws: [
          { id: "higaisha-hogo2", name: "犯罪被害者等基本法", egov_id: "416AC1000000161" },
          { id: "jinken-yogo", name: "人権擁護法（議論）" },
          { id: "kokusai-jinken-kikan", name: "国際人権機関への個人通報制度" },
          { id: "ombudsman", name: "オンブズマン制度・行政苦情" },
        ],
      },
      {
        id: "privacy",
        name: "プライバシー・表現の自由",
        laws: [
          { id: "privacy-ko", name: "プライバシー権（判例法理）" },
          { id: "houdou-jiyuu", name: "報道の自由・取材源秘匿" },
          { id: "hyougen-kisei", name: "表現規制と憲法21条" },
          { id: "name-erase", name: "忘れられる権利（GDPR・日本法）" },
        ],
      },
    ],
  },
  {
    id: "current-topics",
    name: "時事法律トピック",
    nameEn: "Current Legal Issues",
    description: "今話題の法律問題・社会と法の最前線",
    color: "from-orange-900/60 to-orange-800/40 border-orange-700/50 hover:border-orange-500",
    categories: [
      {
        id: "tech-law",
        name: "テクノロジーと法",
        laws: [
          { id: "ai-chosakuken", name: "AIと著作権・学習データの法的問題" },
          { id: "ai-sekinin", name: "AI・自動化による損害の責任論" },
          { id: "deepfake-ho", name: "ディープフェイク・生成AIの規制" },
          { id: "crypto-saiban", name: "暗号資産・NFTをめぐる訴訟・規制" },
          { id: "data-jido", name: "データ経済と独占禁止法" },
        ],
      },
      {
        id: "society-law",
        name: "社会問題と法",
        laws: [
          { id: "gender-saiban", name: "同性婚・選択的夫婦別姓の最新判例" },
          { id: "climate-sosho", name: "気候変動訴訟・環境権の最前線" },
          { id: "gaikokujin-jinken", name: "外国人労働者・難民の人権問題" },
          { id: "hinkon-ho", name: "子どもの貧困・格差と法制度" },
          { id: "seimei-rinri", name: "生命倫理（安楽死・代理出産・ゲノム編集）" },
          { id: "sport-ho", name: "スポーツと法（ドーピング・移籍・ハラスメント）" },
        ],
      },
      {
        id: "security-law",
        name: "安全保障・国際秩序",
        laws: [
          { id: "anzen-hosho", name: "安全保障法制（集団的自衛権・平和安全法制）" },
          { id: "cyber-anpo", name: "サイバー安全保障と国際法" },
          { id: "keizai-anpo", name: "経済安全保障法・先端技術管理" },
          { id: "sensou-kokusaiho", name: "現代の紛争と国際人道法" },
        ],
      },
    ],
  },
];

export type AutoLaw = Law & {
  domain: string;
  category: string;
  addedAt: string;
};

export function getLawById(id: string, autoLaws: AutoLaw[] = []): Law | undefined {
  for (const domain of LAW_DOMAINS) {
    for (const cat of domain.categories) {
      const law = cat.laws.find((l) => l.id === id);
      if (law) return law;
    }
  }
  return autoLaws.find((l) => l.id === id);
}

export function getDomainByLawId(lawId: string): LawDomain | undefined {
  return LAW_DOMAINS.find((d) =>
    d.categories.some((c) => c.laws.some((l) => l.id === lawId))
  );
}
